[build]
    base = "frontend/"
    publish = "dist/"
    command = "npm install && npm run build && pip install -r requirements.txt"

[build.environment]
    SQUID_API_KEY = "86057a2a-3dad-41bd-bda6-d1eaff00515b"
    SQUID_APP_ID = "xt01fcyhd56kellr99"
    SQUID_ENVIRONMENT_ID = "prod"
    SQUID_REGION = "us-east-1.aws"