[build]
    base = "frontend/"
    publish = "dist/"
    command = "npm run build"

[build.environment]
    SQUID_API_KEY = "f37974c2-9c49-4eaf-aa04-794a606bf285"
    SQUID_APP_ID = "xt01fcyhd56kellr99"
    SQUID_ENVIRONMENT_ID = "dev"
    SQUID_REGION = "us-east-1.aws"